Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SimpleSocialNetwork.Models;

namespace SimpleSocialNetwork.Controllers
{
    public class NewsController : Controller
    {
        const int pageSize = 5;
        IUsersRepository _repository;
        User _user;

        public NewsController(IUsersRepository repository,
                              IHttpContextAccessor httpContextAccessor,
                              UserManager<User> userManager)
        {
            _repository = repository;
            var id = userManager.GetUserId(httpContextAccessor.HttpContext.User);
            _user = _repository.GetUserById(id);
        }

        public ActionResult Index(int page = 0)
        {
            if (_user.IsBlocked)
                return View("NoAccess", "Home");

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("~/Views/Post/PostsList.cshtml", GetItemsPage(page));
            }
            return View(GetItemsPage(page));
        }

        private List<Post> GetItemsPage(int page)
        {
            var itemsToSkip = page * pageSize;
            var news = _repository.GetUsersNews(_user).Skip(itemsToSkip).Take(pageSize).ToList();
            return news;
        }

    }
}

Controllers/UserController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SimpleSocialNetwork.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Threading.Tasks;
using SimpleSocialNetwork.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace SimpleSocialNetwork.Controllers
{
    public class UserController : Controller
    {
        IUsersRepository _repository;
        IHostingEnvironment _environment;
        User _user;
        UserManager<User> _userManager;

        public UserController(IUsersRepository repository,
                              IHostingEnvironment environment,
                              IHttpContextAccessor httpContextAccessor,
                              UserManager<User> userManager)
        {
            _repository = repository;
            _environment = environment;
            var id = userManager.GetUserId(httpContextAccessor.HttpContext.User);
            _user = _repository.GetUserById(id);
            _userManager = userManager;
        }

        public async Task<ActionResult> Index()
        {
            _repository.GetUsersMainPageInfo(_user);
            var loggedRoles = (await _userManager.GetRolesAsync(_user)).ToList();
            ViewBag.LoggedUserRoles = loggedRoles;
            ViewBag.UserRoles = loggedRoles;
            if (_user.IsBlocked)
                return RedirectToAction("NoAccess", "Home");
            return View(_user);
        }

        public async Task<ActionResult> MainPage(string userId)
        {
            if(userId == _user.Id)
                return Redirect("~/User");
            User user = _repository.GetUserById(userId);
            _repository.GetUsersMainPageInfo(user);
            var roles = (await _userManager.GetRolesAsync(user)).ToList();
            var loggedRoles = (await _userManager.GetRolesAsync(_user)).ToList();
            ViewBag.LoggedUserRoles = loggedRoles;
            ViewBag.UserRoles = roles;
            if (_user.IsBlocked)
                return RedirectToAction("NoAccess", "Home");
            if (user.IsBlocked)
                return View("BlockedPage", user);
            return View("Index", user);
        }


        public ViewResult Friends(string userId = null)
        {
            if (_user.IsBlocked)
                return View("NoAccess", "Home");
            User user = userId == null ? _user:_repository.GetUserById(userId);

            var friends =_repository.GetUsersFriends(user);
            var followers = user.Followers;
            var followings = user.Following;

            foreach (var friend in friends)
                _repository.GetUsersMainPhoto(friend);
            foreach (var follower in followers)
                _repository.GetUsersMainPhoto(follower);
            foreach (var following in followings)
                _repository.GetUsersMainPhoto(following);

            FriendsRequestsViewModel friendsVM = new FriendsRequestsViewModel
            {
                Friends = user.Friends,
                Followers = user.Followers,
                Following = user.Following
            };

            if (user == _user)
            {
                friendsVM.Requests = user.IncomingFrienshipRequests.Where(r => r.Status == FriendshipStatus.Waiting)
                                                     .Select(r => r.RequestFrom).ToList();
                foreach (var r in friendsVM.Requests)
                    _repository.GetUsersMainPhoto(r);
            }
            return View(friendsVM);
        }

        [HttpGet]
        public ViewResult Update()
        {
            return View(new UserInfoViewModel(_user));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> Update(UserInfoViewModel info)
        {
            if (info.Avatar != null)
            {
                await UpdateAvatar(info.Avatar);
            }

            _user.ChangeInformation(info);
            _repository.Update(_user);
            _repository.Save();
            return RedirectToAction("Index");
        }

        [NonAction]
        public async Task UpdateAvatar(IFormFile avatar)
        {
            string path = "/usersPhotos/avatar" + _user.Id + ".jpg";
            using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
            {
                await avatar.CopyToAsync(fileStream);
            }

            var prevPhoto = _repository.GetUsersMainPhoto(_user);
            if (prevPhoto != null)
                _repository.Remove(prevPhoto);

            Post mainPhoto = new Post { Owner = _user, Date = DateTime.Now, Type = PostType.MainPhoto };
            Photo photo = new Photo { Image = path, Post = mainPhoto };
            _repository.Create(mainPhoto);
            _repository.Create(photo);

            _repository.Update(_user);
            _repository.Save();
        }

        [Authorize(Roles = "moderator")]
        public async Task<ActionResult> Block(string userId)
        {
            User user = _repository.GetUserById(userId);
            var roles = await _userManager.GetRolesAsync(user);
            if (roles.Contains("admin"))
                return await MainPage(userId);
            user.IsBlocked = true;
            _repository.Update(user);
            _repository.Save();
            return await MainPage(userId);
        }

        [Authorize(Roles = "moderator")]
        public Task<ActionResult> Unblock(string userId)
        {
            User user = _repository.GetUserById(userId);
            user.IsBlocked = false;
            _repository.Update(user);
            _repository.Save();
            return MainPage(userId);
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.LoggedUser = _user;
        }
    }
}

Views/Shared/_JustHeaderLayout.cshtml
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>SimpleSocialNetwork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/login.css?Version=4" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="User" asp-action="Index" class="navbar-brand">SimpleSocialNetwork</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="https://github.com/edadasko/SimpleSocialNetwork">@Localizer["source_code"]</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@await Html.PartialAsync("_SelectLanguagePartial")</li>
                    <li><a method="post" asp-controller="Account" asp-action="LogOff" class="navbar-brand">@Localizer["exit"]</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="main_content">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>SimpleSocialNetwork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css?Version=49" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/js/comments.js"></script>
    <script src="~/js/likes.js"></script>
    <script src="~/js/posts.js"></script>
    <script src="~/js/messages.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="User" asp-action="Index" class="navbar-brand">SimpleSocialNetwork</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="https://github.com/edadasko/SimpleSocialNetwork">@Localizer["source_code"]</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@await Html.PartialAsync("_SelectLanguagePartial")</li>
                    <li><a method="post" asp-controller="Account" asp-action="LogOff" class="navbar-brand">@Localizer["exit"]</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class='left_sidebar'>
        <ul>
            <li><a asp-controller="User" asp-action="Index">@Localizer["my_page"]</a></li>
            <li><a asp-controller="User" asp-action="Friends">@Localizer["friends"]</a></li>
            <li><a asp-controller="Message" asp-action="Index">@Localizer["messages"]</a></li>
            <li><a asp-controller="News" asp-action="Index">@Localizer["news"]</a></li>
            <li><a asp-controller="Search" asp-action="Index">@Localizer["search"]</a></li>
        </ul>
    </div>

    <div class="container body-content">
        <div class="main_content">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Views/Shared/_LoginLayout.cshtml
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>SimpleSocialNetwork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/login.css?Version=5" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SimpleSocialNetwork</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="https://github.com/edadasko/SimpleSocialNetwork">@Localizer["source_code"]</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@await Html.PartialAsync("_SelectLanguagePartial")</li>
                    <li><a asp-controller="Account" asp-action="Login" class="navbar-brand">@Localizer["sign_in"]</a></li>
                    <li><a asp-controller="Account" asp-action="Register" class="navbar-brand">@Localizer["sign_up"]</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="main_content">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Extensions
 
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
 
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
 
<form asp-controller="Home" asp-action="SetLanguage"
      asp-route-returnUrl="@Context.Request.GetEncodedPathAndQuery()"
      method="post">
    <select class="select-language" name="culture" onchange="this.form.submit();"
                                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                    asp-items="cultureItems"></select>
</form>