Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using SimpleSocialNetwork.ViewModels;

namespace SimpleSocialNetwork.Models
{
    public class User : IdentityUser
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTime? BirthDay { get; set; }
        public Gender Gender { get; set; }

        public string Country { get; set; }
        public string City { get; set; }
        public string Address { get; set; }

        public string School { get; set; }
        public string University { get; set; }

        public string JobPlace { get; set; }
        public string JobPosition { get; set; }

        public bool IsBlocked { get; set; }

        public ICollection<Friendship> IncomingFrienshipRequests { get; set; }
        public ICollection<Friendship> OutgoingFrienshipRequests { get; set; }

        public ICollection<Post> Posts { get; set; }

        public ICollection<Comment> Comments { get; set; }
        public ICollection<Like> Likes { get; set; }

        public ICollection<Message> MessageFrom { get; set; }
        public ICollection<Message> MessageTo { get; set; }

        [NotMapped]
        public int? Years
        {
            get
            {
                if (BirthDay == null)
                    return null;
                var today = DateTime.Today;
                var age = today.Year - BirthDay.Value.Year;
                if (BirthDay.Value.Date > today.AddYears(-age))
                    age--;
                return age;
            }
        }
        [NotMapped]
        public List<User> Friends
        {
            get
            {
                List<User> friends = new List<User>();

                foreach (var request in IncomingFrienshipRequests.Where
                                  (f => f.Status == FriendshipStatus.Confirmed).ToList())
                    friends.Add(request.RequestFrom);

                foreach (var request in OutgoingFrienshipRequests.Where
                                  (f => f.Status == FriendshipStatus.Confirmed).ToList())
                    friends.Add(request.RequestTo);

                return friends;
            }
        }

        [NotMapped]
        public List<User> Followers
        {
            get
            {
                List<User> followers = new List<User>();

                foreach (var request in IncomingFrienshipRequests.Where
                                  (f => f.Status == FriendshipStatus.Rejected ||
                                  f.Status == FriendshipStatus.Waiting).ToList())
                    followers.Add(request.RequestFrom);
                return followers;
            }
        }

        [NotMapped]
        public List<User> Following
        {
            get
            {
                List<User> following = new List<User>();

                foreach (var request in OutgoingFrienshipRequests.Where
                                  (f => f.Status == FriendshipStatus.Rejected ||
                                  f.Status == FriendshipStatus.Waiting).ToList())
                    following.Add(request.RequestTo);
                return following;
            }
        }


        [NotMapped]
        public List<Post> Photos => Posts.Where(p => p.Type == PostType.PhotoOnly).ToList();

        [NotMapped]
        public Post MainPhoto => Posts.SingleOrDefault(p => p.Type == PostType.MainPhoto);

        [NotMapped]
        public List<Post> WallPosts => Posts.Where(p => p.Type == PostType.Normal).Reverse().ToList();

        [NotMapped]
        public string MainPhotoPath
        {
            get
            {
                try
                {
                    return Posts.SingleOrDefault(p => p.Type == PostType.MainPhoto).Photos.ToList()[0].Image;
                }
                catch(NullReferenceException)
                {
                    return "~/images/no_photo.png";
                }
            }
        }

        public void ChangeInformation(UserInfoViewModel info)
        {
            Name = info.Name;
            Surname = info.Surname;
            BirthDay = info.BirthDay;
            Email = info.Email;
            PhoneNumber = info.PhoneNumber;
            Country = info.Country;
            City = info.City;
            Address = info.Address;
            School = info.School;
            University = info.University;
            JobPlace = info.JobPlace;
            JobPosition = info.JobPosition;
            Gender = info.Gender;
        }

        public User()
        {
            IncomingFrienshipRequests = new List<Friendship>();
            OutgoingFrienshipRequests = new List<Friendship>();
            Posts = new List<Post>();
            Comments = new List<Comment>();
            Likes = new HashSet<Like>();
            MessageFrom = new List<Message>();
            MessageTo = new List<Message>();
        }

        public override string ToString() => Name + " " + Surname;
    }

    public enum Gender
    {
        [Display(Name = "Мужской")]
        Male,
        [Display(Name = "Женский")]
        Female
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using SimpleSocialNetwork.Models;
using SimpleSocialNetwork.ViewModels;

namespace SimpleSocialNetwork.Controllers
{
    public class PostController : Controller
    {
        const int pageSize = 5;

        IUsersRepository _repository;
        IHostingEnvironment _environment;
        User _user;

        public PostController(IUsersRepository repository,
                              IHttpContextAccessor httpContextAccessor,
                              IHostingEnvironment environment,
                              UserManager<User> userManager)
        {
            _repository = repository;
            _environment = environment;
            var id = userManager.GetUserId(httpContextAccessor.HttpContext.User);
            _user = _repository.GetUserById(id);
        }

        public ActionResult Index(int postId)
        {
            var post = _repository.GetPostById(postId);
            return PartialView(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PostViewModel postVM)
        {
            if (postVM.Text == null)
                return RedirectToAction("PostsList");


            var post = new Post()
            {
                Owner = _user,
                Date = DateTime.Now,
                Text = postVM.Text,
                Type = PostType.Normal
            };

            if (postVM.Photo != null)
                await AddPhotoAsync(postVM.Photo, post);

            _repository.Create(post);
            _repository.Save();
            return RedirectToAction("PostsList");
        }

        private async Task AddPhotoAsync(IFormFile photo, Post post)
        {
            string path = "/usersPostPhotos/post" + _user.Id + DateTime.Now.ToString("MMddyyyyHHmmss") + ".jpg";
            using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
            {
                await photo.CopyToAsync(fileStream);
            }

            Photo photoToSave = new Photo { Image = path, Post = post };
            _repository.Create(photoToSave);
        }

        [Route("removePost/{postId}")]
        public ActionResult Remove(int postId)
        {
            var post = _repository.GetPostById(postId);
            _repository.Remove(post);
            _repository.Save();
            return RedirectToAction("PostsList");
        }

        public PartialViewResult PostsList(string userId = null)
        {
            User user = userId == null ? _user : _repository.GetUserById(userId);
            _repository.GetUsersPosts(user);
            return PartialView(user.WallPosts);
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.LoggedUser = _user;
        }
    }
}

Controllers/RolesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SimpleSocialNetwork.Models;

namespace SimpleSocialNetwork.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        UserManager<User> _userManager;
        public RolesController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> SetAdmin(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            await _userManager.AddToRoleAsync(user, "admin");
            await _userManager.AddToRoleAsync(user, "moderator");

            return RedirectToAction("MainPage", "User", new { userId });
        }

        public async Task<IActionResult> SetModerator(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            await _userManager.AddToRoleAsync(user, "moderator");
            return RedirectToAction("MainPage", "User", new { userId });
        }

        public async Task<IActionResult> RemoveModerator(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            await _userManager.RemoveFromRoleAsync(user, "moderator");
            return RedirectToAction("MainPage", "User", new { userId });
        }
    }
}

Controllers/UserController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SimpleSocialNetwork.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Threading.Tasks;
using SimpleSocialNetwork.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace SimpleSocialNetwork.Controllers
{
    public class UserController : Controller
    {
        IUsersRepository _repository;
        IHostingEnvironment _environment;
        User _user;
        UserManager<User> _userManager;

        public UserController(IUsersRepository repository,
                              IHostingEnvironment environment,
                              IHttpContextAccessor httpContextAccessor,
                              UserManager<User> userManager)
        {
            _repository = repository;
            _environment = environment;
            var id = userManager.GetUserId(httpContextAccessor.HttpContext.User);
            _user = _repository.GetUserById(id);
            _userManager = userManager;
        }

        public async Task<ActionResult> Index()
        {
            _repository.GetUsersMainPageInfo(_user);
            var loggedRoles = (await _userManager.GetRolesAsync(_user)).ToList();
            ViewBag.LoggedUserRoles = loggedRoles;
            ViewBag.UserRoles = loggedRoles;
            if (_user.IsBlocked)
                return RedirectToAction("NoAccess", "Home");
            return View(_user);
        }

        public async Task<ActionResult> MainPage(string userId)
        {
            if(userId == _user.Id)
                return Redirect("~/User");
            User user = _repository.GetUserById(userId);
            _repository.GetUsersMainPageInfo(user);
            var roles = (await _userManager.GetRolesAsync(user)).ToList();
            var loggedRoles = (await _userManager.GetRolesAsync(_user)).ToList();
            ViewBag.LoggedUserRoles = loggedRoles;
            ViewBag.UserRoles = roles;
            if (_user.IsBlocked)
                return RedirectToAction("NoAccess", "Home");
            if (user.IsBlocked)
                return View("BlockedPage", user);
            return View("Index", user);
        }


        public ViewResult Friends(string userId = null)
        {
            if (_user.IsBlocked)
                return View("NoAccess", "Home");
            User user = userId == null ? _user:_repository.GetUserById(userId);

            var friends =_repository.GetUsersFriends(user);
            var followers = user.Followers;
            var followings = user.Following;

            foreach (var friend in friends)
                _repository.GetUsersMainPhoto(friend);
            foreach (var follower in followers)
                _repository.GetUsersMainPhoto(follower);
            foreach (var following in followings)
                _repository.GetUsersMainPhoto(following);

            FriendsRequestsViewModel friendsVM = new FriendsRequestsViewModel
            {
                Friends = user.Friends,
                Followers = user.Followers,
                Following = user.Following
            };

            if (user == _user)
            {
                friendsVM.Requests = user.IncomingFrienshipRequests.Where(r => r.Status == FriendshipStatus.Waiting)
                                                     .Select(r => r.RequestFrom).ToList();
                foreach (var r in friendsVM.Requests)
                    _repository.GetUsersMainPhoto(r);
            }
            return View(friendsVM);
        }

        [HttpGet]
        public ViewResult Update()
        {
            return View(new UserInfoViewModel(_user));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> Update(UserInfoViewModel info)
        {
            if (info.Avatar != null)
            {
                await UpdateAvatar(info.Avatar);
            }

            _user.ChangeInformation(info);
            _repository.Update(_user);
            _repository.Save();
            return RedirectToAction("Index");
        }

        [NonAction]
        public async Task UpdateAvatar(IFormFile avatar)
        {
            string path = "/usersPhotos/avatar" + _user.Id + ".jpg";
            using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
            {
                await avatar.CopyToAsync(fileStream);
            }

            var prevPhoto = _repository.GetUsersMainPhoto(_user);
            if (prevPhoto != null)
                _repository.Remove(prevPhoto);

            Post mainPhoto = new Post { Owner = _user, Date = DateTime.Now, Type = PostType.MainPhoto };
            Photo photo = new Photo { Image = path, Post = mainPhoto };
            _repository.Create(mainPhoto);
            _repository.Create(photo);

            _repository.Update(_user);
            _repository.Save();
        }

        [Authorize(Roles = "moderator")]
        public async Task<ActionResult> Block(string userId)
        {
            User user = _repository.GetUserById(userId);
            var roles = await _userManager.GetRolesAsync(user);
            if (roles.Contains("admin"))
                return await MainPage(userId);
            user.IsBlocked = true;
            _repository.Update(user);
            _repository.Save();
            return await MainPage(userId);
        }

        [Authorize(Roles = "moderator")]
        public Task<ActionResult> Unblock(string userId)
        {
            User user = _repository.GetUserById(userId);
            user.IsBlocked = false;
            _repository.Update(user);
            _repository.Save();
            return MainPage(userId);
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.LoggedUser = _user;
        }
    }
}

Views/User/BlockedPage.cshtml
@model User
@inject IViewLocalizer Localizer
@{
    User ownerUser = (User)ViewBag.LoggedUser;
    List<string> ownerRoles = (List<string>)ViewBag.LoggedUserRoles;
}

<div class="container-fluid">
    <div class="main-section-data">
        <div class="row">
            <div class="col-md-4 col-sm-4 pd-left-none no-pd main-column">
                <div class="user-data full-width">
                    <div class="user-profile">
                        <div class="username-dt">
                            <div class="usr-pic">
                                <img src="@Url.Content(@Model.MainPhotoPath)" alt="">
                            </div>
                        </div>
                        <div class="user-specs">
                            <h3>@Model</h3>
                        </div>

                        @if (ownerRoles.Contains("moderator"))
                        {
                            <div class="requests-info">
                                <button type="submit" class="btn btn-primary button-main-page"
                                        onclick="@("window.location.href='" +
                                        @Url.Action("Unblock", "User",
                                        new { userId = Model.Id }) + "'");">@Localizer["unblock"]</button>
                            </div>
                        }

                    </div>
                </div>
                </div>

            <div class="col-md-8 col-sm-8 pd-left-none no-pd main-column">
                <h3>@Localizer["block_info"]</h3>
            </div>
        </div>
    </div>
</div>

Views/User/Index.cshtml
@model User
@inject IViewLocalizer Localizer
@{
    User ownerUser = (User)ViewBag.LoggedUser;
    List<string> roles = (List<string>)ViewBag.UserRoles;
    List<string> ownerRoles = (List<string>)ViewBag.LoggedUserRoles;
}

<div class="container-fluid">
    <div class="main-section-data">
        <div class="row">
            <div class="col-md-4 col-sm-4 pd-left-none no-pd main-column">
                <div class="user-data full-width">
                    <div class="user-profile">
                        <div class="username-dt">
                            <div class="usr-pic">
                                <img src="@Url.Content(@Model.MainPhotoPath)" alt="">
                            </div>
                        </div>
                        <div class="user-specs">
                            <h3>@Model</h3>
                            @if (roles.Contains("admin"))
                            {
                                <p>@Localizer["admin"]</p>
                            }
                            else if (roles.Contains("moderator"))
                            {
                                <p>@Localizer["moderator"]</p>
                            }
                        </div>
                        @if (Model != ownerUser)
                        {
                            <button type="submit"
                            userToId ="@Model.Id" class="btn btn-primary button-main-page" 
                            onclick="@("window.location.href='" + @Url.Action("Index", "Message",
                            new { userWithId = @Model.Id }) + "'");">@Localizer["send_message"]</button>
                            <div class="requests-info">
                                @if(ownerUser.Friends.Contains(Model))
                                {
                                    <p>@Localizer["your_friend"]</p>
                                    <button type="submit" class="btn btn-primary button-main-page"
                                        onclick="@("window.location.href='" +
                                        @Url.Action("Remove", "Friendship", new { userId = Model.Id }) + "'");">@Localizer["remove_friend"]</button>
                                }
                                else if (ownerUser.Followers.Contains(Model))
                                {
                                    var text = Model.Gender == Gender.Male ? @Localizer["follower_he"].Value : @Localizer["follower_she"].Value;
                                    <p>@text</p>
                                    
                                    <button type="submit" class="btn btn-primary button-main-page"
                                        onclick="@("window.location.href='" +
                                        @Url.Action("ConfirmRequest", "Friendship", new { userId = Model.Id }) + "'");">@Localizer["add_friend"]</button>
                                }
                                else if (ownerUser.Following.Contains(Model))
                                {
                                    <p>@Localizer["request_send"]</p>
                                    <button type="submit" class="btn btn-primary button-main-page"
                                        onclick="@("window.location.href='" +
                                        @Url.Action("CancelRequest", "Friendship", new { userId = Model.Id }) + "'");">@Localizer["cancel_request"]</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary button-main-page"
                                        onclick="@("window.location.href='" +
                                        @Url.Action("AddToFriends", "Friendship", new { userId = Model.Id }) + "'");">@Localizer["add_friend"]</button>
                                }
                            </div>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-primary button-main-page"  
                            onclick="@("window.location.href='" + @Url.Action("Update", "User") + "'");">@Localizer["edit_page"]</button>
                        }

                        @if ((ownerRoles.Contains("admin") && !roles.Contains("admin")) ||
                            (ownerRoles.Contains("moderator") && !roles.Contains("moderator")))
                        {
                            <div class="admin-area">
                                @if (ownerRoles.Contains("admin"))
                                {
                                    if (!roles.Contains("admin"))
                                    {
                                        <button type="submit" class="btn btn-primary button-main-page"
                                            onclick="@("window.location.href='" +
                                            @Url.Action("SetAdmin", "Roles",
                                            new { userId = Model.Id }) + "'");">@Localizer["appoint_as_admin"].Value</button>
                                    }

                                    if (!roles.Contains("moderator"))
                                    {
                                        <button type="submit" class="btn btn-primary button-main-page"
                                            onclick="@("window.location.href='" +
                                            @Url.Action("SetModerator", "Roles",
                                            new { userId = Model.Id }) + "'");">@Localizer["appoint_as_moderator"].Value</button>
                                    }
                                    else if (!roles.Contains("admin"))
                                    {
                                        <button type="submit" class="btn btn-danger button-main-page-danger"
                                            onclick="@("window.location.href='" +
                                            @Url.Action("RemoveModerator", "Roles",
                                            new { userId = Model.Id }) + "'");">@Localizer["remove_moderator"].Value</button>
                                    }
                                }

                                @if ((ownerRoles.Contains("moderator") && !roles.Contains("moderator")))
                                {
                                    <button type="submit" class="btn btn-danger button-main-page-danger"
                                        onclick="@("window.location.href='" +
                                        @Url.Action("Block", "User",
                                        new { userId = Model.Id }) + "'");">@Localizer["block"].Value</button>
                                }
                            </div>
                        }

                    </div>
                </div>
                <div class="friends-main full-width">
                    <div class="friends-main-title">
                        <h3>@Localizer["friends"]<span>@Model.Friends.Count</span></h3>
                    </div>
                    <div class="friends-main-list">
                        @foreach (var friend in Model.Friends.Take(5))
                        {
                            <div class="friends-main-usd">
                                <img src="@Url.Content(@friend.MainPhotoPath)" alt="">
                                <div class="friends-text">
                                    @Html.ActionLink(@friend.ToString(), "MainPage", new { userId = @friend.Id })
                                </div>
                            </div>
                        }
                    </div>
                    <div class="view-more">
                        @Html.ActionLink(@Localizer["all_friends"].Value, "Friends", new { userId = @Model.Id })
                    </div>
                </div>
                </div>

            <div class="col-md-8 col-sm-8 pd-left-none no-pd main-column">
                @{await Html.RenderPartialAsync("Information", new UserInfoViewModel(Model));}

                @if (Model == ownerUser)
                {
                    <div class="container-fluid">

                        <div class="post-area">
                            <div class="form-group">
                                <form asp-action="Create" asp-controller="Post" method="POST" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#postsArea" enctype="multipart/form-data">
                                    <textarea name = "Text" id="postTextArea" class="form-control" rows="3" placeholder="@Localizer["new_post"]"></textarea>
                                    <div class="container-fluid">
                                         <div class="row">
                                             <div class="col-md-10 col-sm-10 pd-right-none no-pd">
                                                 <label id="attached-photo-name" for="photoPostInput" class="btn">@Localizer["choose_photo"]</label>
                                                 <input name = "Photo" id="photoPostInput" type="file" class="form-control add-post-image" />
                                             </div>
                                             <div class="col-md-2 col-sm-2 pd-right-none no-pd add-post-button-col">
                                                 <input type="submit" value="@Localizer["add_post"]" class="btn btn-primary add-post-button"/>
                                             </div>
                                         </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                }

                <div class="posts" id="postsArea">
                    @{await Html.RenderPartialAsync("~/Views/Post/PostsList.cshtml", @Model.WallPosts);}
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/lib/jquery-unobtrusive-ajax/jquery.unobtrusive-ajax.js"></script>
<script>
    $("#photoPostInput").change(function() {
      $("#attached-photo-name").text(this.files[0].name);
    });
</script>

Views/User/Update.cshtml
@model UserInfoViewModel
@inject IViewLocalizer Localizer

<div class="update-page">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name" class="control-label">@Localizer["name"]</label>
            <input type="text" asp-for="Name" class="form-control" value="@Model.Name" required/>
        </div>
        <div class="form-group">
            <label asp-for="Surname" class="control-label">@Localizer["surname"]</label>
            <input type="text" asp-for="Surname" class="form-control" value="@Model.Surname" required/>
        </div>

        <div class="form-group">
            <label>@Localizer["avatar"]</label>
            <input name="Avatar" type="file" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Gender" class="control-label">@Localizer["gender"]</label>
            <br />
            <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()"></select>
        </div>


        <div class="form-group">
            <label asp-for="BirthDay" class="control-label">@Localizer["birthday"]</label>
            <input type="date" asp-for="BirthDay" id="@Model.BirthDay" class="form-control"/>
        </div>


        <hr />

        <div class="form-group">
            <label asp-for="Country" class="control-label">@Localizer["country"]</label>
            <input type="text" asp-for="Country" class="form-control" value="@Model.Country" />
        </div>

        <div class="form-group">
            <label asp-for="City" class="control-label">@Localizer["city"]</label>
            <input type="text" asp-for="City" id="@Model.City" class="form-control"/>
        </div>

        <div class="form-group">
            <label asp-for="Address" class="control-label">@Localizer["address"]</label>
            <input type="text" asp-for="Address" id="@Model.Address" class="form-control"/>
        </div>

        <hr />

        <div class="form-group">
            <label asp-for="Email" class="control-label">@Localizer["email"]</label>
            <input type="email" asp-for="Email" class="form-control" value="@Model.Email" />
        </div>

         <div class="form-group">
            <label asp-for="PhoneNumber" class="control-label">@Localizer["phone_num"]</label>
            <input type="text" asp-for="PhoneNumber" class="form-control" value="@Model.PhoneNumber" />
        </div>

        <hr />

        <div class="form-group">
            <label asp-for="School" class="control-label">@Localizer["school"]</label>
            <input type="text" asp-for="School" class="form-control" value="@Model.School" />
        </div>

         <div class="form-group">
            <label asp-for="University" class="control-label">@Localizer["university"]</label>
            <input type="text" asp-for="University" class="form-control" value="@Model.University" />
        </div>

        <hr />

        <div class="form-group">
            <label asp-for="JobPlace" class="control-label">@Localizer["job_place"]</label>
            <input type="text" asp-for="JobPlace" class="form-control" value="@Model.JobPlace" />
        </div>

         <div class="form-group">
            <label asp-for="JobPosition" class="control-label">@Localizer["job_position"]</label>
            <input type="text" asp-for="JobPosition" class="form-control" value="@Model.JobPosition" />
        </div>

        <hr />



        <div class="form-group">
            <input type="submit" value="@Localizer["save"]" class="btn btn-default" />
        </div>
    </form>
</div>